ALTER TABLE stickies ADD COLUMN IF NOT EXISTS pos_x INTEGER;
ALTER TABLE stickies ADD COLUMN IF NOT EXISTS pos_y INTEGER;
ALTER TABLE stickies ADD COLUMN IF NOT EXISTS width INTEGER NOT NULL DEFAULT 340;
ALTER TABLE stickies ADD COLUMN IF NOT EXISTS height INTEGER NOT NULL DEFAULT 274;
